apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemma-embedding-storage
  namespace: edg-demo
  labels:
    app: gemma-embedding-download
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
