apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mistral-model-storage
  namespace: edg-demo
  labels:
    app: mistral-download
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
